In [1]:
import pandas as pd
import numpy as np

In [2]:
crime_anal_police = pd.read_csv('../../data/02. crime_in_Seoul.csv', thousands=',', encoding='euc-kr') 
crime_anal_police

     관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0    중부서      2      2      3      2    105     65   1395    477   1355   1170
1    종로서      3      3      6      5    115     98   1070    413   1278   1070
2   남대문서      1      0      6      4     65     46   1153    382    869    794
3   서대문서      2      2      5      4    154    124   1812    738   2056   1711
4    혜화서      3      2      5      4     96     63   1114    424   1015    861
5    용산서      5      5     14     14    194    173   1557    587   2050   1704
6    성북서      2      2      2      1     86     71    953    409   1194   1015
7   동대문서      5      5     13     13    173    146   1981    814   2548   2227
8    마포서      8      8     14     10    294    247   2555    813   2983   2519
9   영등포서     14     12     22     20    295    183   2964    978   3572   2961
10   성동서      4      4      9      8    126    119   1607    597   1612   1395
11   동작서      5      5      9      5    285    139   1865    661   1910   1587
12   광진서      4      4     14     26    240    220   3026   1277   2625   2180
13   서부서      2      2      2      1     70     59    819    293   1192   1038
14   강북서      7      8     14     13    153    126   1434    618   2649   2348
15   금천서      3      4      6      6    151    122   1567    888   2054   1776
16   중랑서     13     12     11      9    187    148   2135    829   2847   2407
17   강남서      3      3     15     12    300    225   2411    984   2465   2146
18   관악서      9      8     12     14    320    221   2706    827   3298   2642
19   강서서      7      8     13     13    262    191   2096   1260   3207   2718
20   강동서      4      3      6      8    156    123   2366    789   2712   2248
21   종암서      3      3      3      3     64     53    832    332   1015    840
22   구로서      8      6     15     11    281    164   2335    889   3007   2432
23   서초서      7      4      8      5    334    193   1982    905   1852   1607
24   양천서      3      5      6      3    120    105   1890    672   2509   2030
25   송파서     11     10     13     10    220    178   3239   1129   3295   2786
26   노원서     10     10      7      7    197    121   2193    801   2723   2329
27   방배서      1      2      1      1     59     56    653    186    547    491
28   은평서      1      1      7      5     96     82   1095    418   1461   1268
29   도봉서      3      3      9     10    102    106   1063    478   1487   1303
30   수서서     10      7      6      6    149    124   1439    666   1819   1559

In [3]:
import googlemaps #googlemaps 모듈을 import

In [4]:
gmaps_key = "AIzaSyCjpe11vLZPL5-VU1RpJtlai74qVyeiUws"
gmaps = googlemaps.Client(key=gmaps_key)

In [5]:
gmaps.geocode('서울중부경찰서', language='ko')

[{'address_components': [{'long_name': '２７',
    'short_name': '２７',
    'types': ['premise']},
   {'long_name': '수표로',
    'short_name': '수표로',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '을지로동',
    'short_name': '을지로동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '중구',
    'short_name': '중구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '100-032',
    'short_name': '100-032',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 중구 을지로동 수표로 ２７',
  'geometry': {'location': {'lat': 37.5636465, 'lng': 126.9895796},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.56499548029149,
     'lng': 126.9909285802915},
    'southwest': {'lat': 37.56229751970849, 'lng': 126.9882306197085}}},
  'place_id': 'ChIJc-9q5uSifDURLhQmr5wkXmc',
  'types': ['establishment', 'point_of_interest', 'police']}]

In [6]:
station_name= []

for name in crime_anal_police['관서명']:
    station_name.append('서울'+str(name[:-1])+'경찰서')
    
station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [7]:
station_address = []
station_lat= []
station_lng= []

for name in station_name:
    tmp = gmaps.geocode(name,language='ko')
    station_address.append(tmp[0].get('formatted_address'))
    tmp_loc = tmp[0].get("geometry")
    station_lat.append(tmp_loc['location']['lat']) 
    station_lng.append(tmp_loc['location']['lng'])

In [8]:
station_address

['대한민국 서울특별시 중구 을지로동 수표로 ２７',
 '대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 ４６',
 '대한민국 서울특별시 중구 남대문로5가 한강대로 ４１０',
 '대한민국 서울특별시 서대문구 미근동 통일로 １１３',
 '대한민국 서울특별시 종로구 종로1.2.3.4가동 창경궁로 １１２−１６',
 '대한민국 서울특별시 용산구 원효로1가 25',
 '대한민국 서울특별시 성북구 삼선동5가 301',
 '대한민국 서울특별시 동대문구 청량리동 약령시로21길 ２９',
 '대한민국 서울특별시 마포구 아현동 ６１８−１',
 '대한민국 서울특별시 영등포구 당산동3가 ２−１１',
 '대한민국 서울특별시 성동구 행당동 １９２−８',
 '대한민국 서울특별시 동작구 노량진동 ７２',
 '대한민국 서울특별시 광진구 구의1동 자양로 １６７',
 '대한민국 서울특별시 은평구 녹번동 １７７−１５',
 '대한민국 서울특별시 강북구 번1동 ４１５−１５',
 '대한민국 서울특별시 관악구 신림동 ５４４',
 '대한민국 서울특별시 중랑구 신내1동 신내역로3길 ４０−１０',
 '대한민국 서울특별시 강남구 대치동 ９９８',
 '대한민국 서울특별시 관악구 봉천동',
 '대한민국 서울특별시 양천구 신월동 화곡로 ７３',
 '대한민국 서울특별시 강동구 성내1동 성내로 ５７',
 '대한민국 서울특별시 성북구 종암동 ３−１２６０',
 '대한민국 서울특별시 구로구 가마산로 235',
 '대한민국 서울특별시 서초구 서초3동 반포대로 １７９',
 '대한민국 서울특별시 양천구 신정6동 목동동로 ９９',
 '대한민국 서울특별시 송파구 가락본동 9',
 '대한민국 서울특별시 노원구 하계동 노원로 ２８３',
 '대한민국 서울특별시 서초구 방배2동 방배천로 54',
 '대한민국 서울특별시 은평구 불광2동 연서로 ３６５',
 '대한민국 서울특별시 도봉구 창4동 노해로 ４０３',
 '대한민국 서울특별시 강남구 개포동 개포로 ６１７']

In [9]:
station_lat

[37.5636465,
 37.5755578,
 37.5547584,
 37.5647848,
 37.5718401,
 37.538649,
 37.5897271,
 37.58506149999999,
 37.550814,
 37.5257884,
 37.5617309,
 37.5130685,
 37.542873,
 37.6021405,
 37.6373881,
 37.4814051,
 37.618692,
 37.5094352,
 37.4743789,
 37.5397827,
 37.528511,
 37.6020592,
 37.494931,
 37.4956054,
 37.5165667,
 37.5019065,
 37.6423605,
 37.4815453,
 37.6283597,
 37.6533589,
 37.49349]

In [10]:
gu_name = []

for name in station_address:
    tmp = name.split()
    
    tmp_gu = [gu for gu in tmp if gu[-1] == '구'][0]
    gu_name.append(tmp_gu)

crime_anal_police['구별'] = gu_name
crime_anal_police

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구
5,용산서,5,5,14,14,194,173,1557,587,2050,1704,용산구
6,성북서,2,2,2,1,86,71,953,409,1194,1015,성북구
7,동대문서,5,5,13,13,173,146,1981,814,2548,2227,동대문구
8,마포서,8,8,14,10,294,247,2555,813,2983,2519,마포구
9,영등포서,14,12,22,20,295,183,2964,978,3572,2961,영등포구
10,성동서,4,4,9,8,126,119,1607,597,1612,1395,성동구
11,동작서,5,5,9,5,285,139,1865,661,1910,1587,동작구
12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,광진구
13,서부서,2,2,2,1,70,59,819,293,1192,1038,은평구
14,강북서,7,8,14,13,153,126,1434,618,2649,2348,강북구
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,관악구
16,중랑서,13,12,11,9,187,148,2135,829,2847,2407,중랑구
17,강남서,3,3,15,12,300,225,2411,984,2465,2146,강남구
18,관악서,9,8,12,14,320,221,2706,827,3298,2642,관악구
19,강서서,7,8,13,13,262,191,2096,1260,3207,2718,양천구
20,강동서,4,3,6,8,156,123,2366,789,2712,2248,강동구
21,종암서,3,3,3,3,64,53,832,332,1015,840,성북구
22,구로서,8,6,15,11,281,164,2335,889,3007,2432,구로구
23,서초서,7,4,8,5,334,193,1982,905,1852,1607,서초구
24,양천서,3,5,6,3,120,105,1890,672,2509,2030,양천구
25,송파서,11,10,13,10,220,178,3239,1129,3295,2786,송파구
26,노원서,10,10,7,7,197,121,2193,801,2723,2329,노원구
27,방배서,1,2,1,1,59,56,653,186,547,491,서초구
28,은평서,1,1,7,5,96,82,1095,418,1461,1268,은평구
29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,도봉구
30,수서서,10,7,6,6,149,124,1439,666,1819,1559,강남구

In [11]:
crime_anal_police[crime_anal_police['관서명']=='금천서']

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,관악구

In [12]:
crime_anal_police.loc[crime_anal_police['관서명'] == '금천서',['구별']]= '금천구'
crime_anal_police[crime_anal_police['관서명']=='금천서']

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구

In [13]:
crime_anal_police.to_csv('../../data/seoul_crime_include_gu_name.csv', sep=',', encoding='utf-8')

In [14]:
crime_anal_police.sort_values(['구별']).head(10)

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
30,수서서,10,7,6,6,149,124,1439,666,1819,1559,강남구
17,강남서,3,3,15,12,300,225,2411,984,2465,2146,강남구
20,강동서,4,3,6,8,156,123,2366,789,2712,2248,강동구
14,강북서,7,8,14,13,153,126,1434,618,2649,2348,강북구
18,관악서,9,8,12,14,320,221,2706,827,3298,2642,관악구
12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,광진구
22,구로서,8,6,15,11,281,164,2335,889,3007,2432,구로구
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구
26,노원서,10,10,7,7,197,121,2193,801,2723,2329,노원구
29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,도봉구

In [15]:
crime_anal = pd.pivot_table(crime_anal_police, index='구별', aggfunc=np.sum)
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
관악구    221    320     14     12      8      9    827   2706   2642   3298
광진구    220    240     26     14      4      4   1277   3026   2180   2625

In [16]:
crime_anal['강간검거율'] = crime_anal['강간 검거']/crime_anal['강간 발생']*100
crime_anal['강도검거율'] = crime_anal['강도 검거']/crime_anal['강도 발생']*100
crime_anal['살인검거율'] = crime_anal['살인 검거']/crime_anal['살인 발생']*100
crime_anal['절도검거율'] = crime_anal['절도 검거']/crime_anal['절도 발생']*100
crime_anal['폭력검거율'] = crime_anal['폭력 검거']/crime_anal['폭력 발생']*100

del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [17]:
con_list=['강간검거율', '강도검거율','살인검거율','절도검거율','폭력검거율']

for column in con_list:
        crime_anal.loc[crime_anal[column]>100, column] = 100
        
crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [18]:
crime_anal.rename(columns={'강간 발생':'강간', 
                           '강도 발생':'강도',
                           '살인 발생':'살인', 
                           '절도 발생':'절도', 
                           '폭력 발생':'폭력'}, inplace=True)
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [19]:
from sklearn import preprocessing #정규화를 손쉽게 하기 위해서

In [20]:
col = ['강간','강도','살인','절도','폭력']

x = crime_anal[col].values
min_max_scaler = preprocessing.MinMaxScaler() #정규화(최대값을 1로 놓고 나머지 값들을 비율로 맞추는 것)

x_scaled = min_max_scaler.fit_transform(x.astype(float)) #타임 설정하기.여기서는 각 값들을 float형태로 설정
crime_anal_norm = pd.DataFrame(x_scaled, columns=col, index= crime_anal.index)

col2 = ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_anal_norm[col2] = crime_anal[col2] 
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619

In [21]:
import platform

from matplotlib import font_manager,rc
from matplotlib import pyplot as plt
%matplotlib inline
plt.rcParams['axes.unicode_minus']=False

if platform.system()=='Darwin':
    rc('font',family='AppleGothic')
elif platform.system()=='Windows':
    path="c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font',family=font_name)

else:
    print('Unknown System... Sorry~~')

In [23]:
import seaborn as sns